# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 22:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_readlater'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributors',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
